METHOD:
  method: 'AM'
  temp: 15
  alpha: 0.9
  K: 10
  loss_weights: [1.0, 10, 1.0]  # [Xent, H(Y), H(Y|X)]
  lr_lp: 1e-4
  iter: 1000
  entropies: ['Shannon', 'Alpha', 'Alpha'] #['Shannon', 'Alpha', 'Alpha'] # [Xent, H(Y), H(Y|X)]
  alpha_values: [5.0, 5.0, 5.0] # [Xent, H(Y), H(Y|X)]
  PLC: True
  use_tuned_alpha_values: True